linux-system-roles/.github

inventory/group_vars/active_roles.yml
inventory/host_vars/journald.yml
inventory/inventory.yml
playbooks/files/.github/dependabot.yml
playbooks/templates/.github/workflows/ansible-lint.yml
playbooks/templates/.github/workflows/ansible-managed-var-comment.yml
playbooks/templates/.github/workflows/ansible-plugin-scan.yml
playbooks/templates/.github/workflows/ansible-test.yml
playbooks/templates/.github/workflows/changelog_to_tag.yml
playbooks/templates/.github/workflows/codeql.yml
playbooks/templates/.github/workflows/markdownlint.yml
playbooks/templates/.github/workflows/python-unit-test.yml
playbooks/templates/.github/workflows/shellcheck.yml
playbooks/templates/.github/workflows/weekly_ci.yml
playbooks/update_files.yml

The `set-output` has been deprecated - see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Some of the actions have been updated to fix this issue - update those actions
The `create-release` action has been deprecated
https://github.com/actions/create-release
the highest rated replacement is
https://github.com/marketplace/actions/create-release
reset existing commit after rebase to add without another commit

deprecate set-output; update actions

---

README.md

Without gh credentials caching I was prompted to enter username and password on every push because repos are cloned with HTTPS

docs: Extend docs for how to prepare GH for automation using

---

inventory/group_vars/active_roles.yml
inventory/host_vars/network.yml
inventory/host_vars/rhc.yml
playbooks/files/.commitlintrc.js
playbooks/templates/.github/workflows/commitlint.yml
playbooks/update_files.yml

- Add commitlint.config.js as a file for visibility
- Do not pull the config
- Do not set redundant env vars, just use them inline
- Quote github.event.pull_request.title in case it contains shell metacharacter
- Do not ignore tests/roles/candlepin in rhc role

ci(commitlint): Apply feedback to commitlint github action

---

inventory/group_vars/active_roles.yml

The major version bump is because tox-lsr 3 drops support
for tox version 2.  If you are using tox 2 you will need to
upgrade to tox 3 or 4.
tox-lsr 3.0.0 adds support for tox 4, commitlint, and ansible-lint-collection
See https://github.com/linux-system-roles/tox-lsr/releases/tag/3.0.0
for full release notes

ci: update tox-lsr to version 3.0.0

---

inventory/group_vars/active_roles.yml
playbooks/files/.github/pull_request_template.md
playbooks/templates/.github/workflows/commitlint.yml

Adding the same template for any pull request.
It is possible to add different templates, e.g. have different fields requested for fix and for feat, but that's pretty ugly, described in https://stackoverflow.com/questions/73771068/multiple-templates-for-pull-requests-on-github
So users must do couple clicks to navigate to their template, it's not possible to set the template based on the PR title prefix. So it is easier to just have one template and then rely on contributers common sense to decide how to fill in the template.
Also, removing commits check from commitlint and only keep PR title check. Only PR title because the description can use all benefits of md formatting and e.g. have lines longer than 72 symbols etc.

Add pull request template and run commitlint on PR title only

---

playbooks/templates/.github/workflows/python-unit-test.yml

We use the setup-python github action.  This has dropped support for
python 2.7.  Instead, just manually install the python2.7 package.

ci: fix python 2.7 CI tests by manually installing python2.7 package

---

inventory/group_vars/active_roles.yml

ansible-lint has recently added a check for this.  It flags a lot of our test
code, and some of our role code that uses nested roles.
There is no easy way to disable it for these cases only.  It would be a
tremendous amount of work to add `# noqa` comments everywhere.
The use of `.ansible-lint-ignore` would be a maintenance burden (cannot use
tests/tests_*.yml or other similar wildcard to match all test files), would
still issue a lot of warning messages, and would not solve all of the problems.
The only way for now is to skip this rule.

ci: ansible-lint - ignore var-naming[no-role-prefix]

---

inventory/group_vars/active_roles.yml
inventory/host_vars/ad_integration.yml
inventory/host_vars/ha_cluster.yml
inventory/host_vars/mssql.yml
inventory/host_vars/rhc.yml
inventory/host_vars/selinux.yml
inventory/host_vars/timesync.yml
inventory/host_vars/tlog.yml
inventory/host_vars/vpn.yml
playbooks/files/.markdownlint.yaml
playbooks/templates/.github/workflows/ansible-lint.yml
playbooks/templates/.github/workflows/ansible-test.yml
playbooks/templates/.github/workflows/codeql.yml
playbooks/templates/.github/workflows/python-unit-test.yml

The latest Ansible repo gating tests run ansible-lint against
the collection format instead of against individual roles.
We have to convert the role to collection format before running
ansible-test.
Role developers can run this locally using
`tox -e collection,ansible-lint-collection`
See https://github.com/linux-system-roles/tox-lsr/pull/125
ha_cluster - add to python_roles
metrics - fix ansible-lint

ci: run ansible-lint against the collection

---

inventory/host_vars/ha_cluster.yml
inventory/host_vars/timesync.yml
inventory/host_vars/vpn.yml

add wokeignore for .ansible-lint sanity skips

add wokeignore rule for ansible-lint sanity skip

---

inventory/group_vars/active_roles.yml
playbooks/role_templates/ha_cluster/.github/workflows/python-unit-test.yml
playbooks/templates/.github/workflows/python-unit-test.yml
playbooks/templates/.yamllint.yml

The latest version of virtualenv does not support creating
python 2.7 virtualenvs.  Change our CI tests to restrict the version
of virtualenv<20.22.0 and tox<4.15 for py27 environments
Move pylint, flake8, and black checks to the py310 environment
which is currently supported by ansible-core 2.17 and its related
checkers such as ansible-lint and ansible-test
pylint now uses ansible-core 2.17 and restricts the version of
pylint to 3.1.0 which is the version used by ansible-test 2.17
Remove `extends: default` for .yamllint.yml.  The latest version
of ansible-lint will automatically incorporate local yamllint
settings unless there is an `extends:`.
The above changes require some fixes to the role code.
For more information, see
https://github.com/linux-system-roles/tox-lsr/pull/168
and …

ci: tox-lsr 3.4.0 - fix py27 tests; move other checks to py310

---

playbooks/templates/.ansible-lint

This fixes the breakage of ansible-test.
We want to advertise support for ansible 2.14 since some of
our collections will be supported for a long time on this
version.  The latest version of ansible-lint requires 2.15
in meta/runtime.yml, but it also adds support for a way to
tell ansible-lint other versions which are acceptable, using
the new `supported_ansible_also` configuration option
in .ansible-lint
With this fix, we can support both the latest version of
ansible-test and ansible-lint.
See https://github.com/linux-system-roles/auto-maintenance/pull/341
for more information.

ci: Add supported_ansible_also to .ansible-lint

---

playbooks/templates/.github/workflows/ansible-lint.yml
playbooks/templates/.github/workflows/ansible-test.yml

the change made for
https://github.com/ansible/ansible-lint/commit/b4018c22f8fe8371bd6845d0cd62cebea54ce012
means that ansible-lint now needs an absolute path for the working directory
Go ahead and make ansible-test use absolute path too just in case they decide
to make the same change.

ci: ansible-lint action now requires absolute directory

---

playbooks/update_files.yml

According to the Ansible team, support for listing platforms in
role `meta/main.yml` files is being removed.
Instead, they recommend using `galaxy_tags`
https://github.com/ansible/ansible/blob/stable-2.17/changelogs/CHANGELOG-v2.17.rst
"Remove the galaxy_info field platforms from the role templates"
https://github.com/ansible/ansible/issues/82453
Many roles already have tags such as "rhel", "redhat", "centos", and "fedora".
I propose that we ensure all of the system roles have these tags.
Some of our roles support Suse, Debian, Ubuntu, and others.
We should add tags for those e.g. the ssh role already has tags for "debian" and "ubuntu".
In addition - for each version listed under `platforms.EL` - add a tag like `elN`.
Q: Why not use a delimiter between the platform and the version e.g. …

fix: add support for EL10

---

playbooks/scripts/update_meta_main.py

mssql is the only role that doesn't support EL 10, adding a workaround for it

Do not append el10 tag for mssql

---

playbooks/templates/.github/workflows/tft.yml
playbooks/templates/plans/README-plans.md
playbooks/templates/plans/general.fmf

* Add a preparation job to run on managed nodes
* Update instructions to run tests locally
* From tft workflow, remove condition for commenter author_association. This would require us to add all trusted users, running workflow is not dangerous.
* Keep the plan minimal, only run prep steps required to install beakerlib

ci: Update fmf plan to add a separate job to prepare managed nodes

---

inventory/group_vars/active_roles.yml
playbooks/templates/.github/workflows/tft.yml
playbooks/templates/.github/workflows/tft_citest_bad.yml

* Remove plan from role dir, it's too complicated and long to run tests from tmt
* Use plan from linux-system-roles/tft-tests
* Move getting datetime to testing-farm job where it's used
* Add a workflow for running [citest_bad]
* Bump sclorg/testing-farm-as-github-action to v3
* Move concurrency group to first job
* Dump GitHub context

ci: Add workflow for ci_test bad, use remote fmf plan

---

playbooks/templates/.github/workflows/tft.yml
playbooks/templates/.github/workflows/tft_citest_bad.yml

* Add "BusinessUnit": "system_roles" environment setting to tag our jobs in Testing farm
* Add tmt_plan_filter to run additional workflows besides general
* Allow more [citest bad] comment formats
* Get memory and supported platforms info from the PR ref
* Move LINUXSYSTEMROLES_USER to vars and use it everywhere in tft.yml
* Remove extra GITHUB_ORG definition
* Add missing slash in ARTIFACTS_URL

ci: Add tags to TF workflow, allow more [citest bad] formats

---

inventory/host_vars/metrics.yml
playbooks/templates/.github/workflows/ansible-test.yml

The ansible-test github action does not use a supported version
of ansible-core by default.
https://github.com/ansible-community/ansible-test-gh-action?tab=readme-ov-file#ansible-core-version
We have to set it in our action.  Using `stable-2.17` as that is the latest stable version.

ci: ansible-test action now requires ansible-core version

---

inventory/group_vars/active_roles.yml
inventory/host_vars/network.yml
playbooks/scripts/update_meta_main.py
playbooks/templates/tests/vars/rh_distros_vars.yml
playbooks/update_files.yml

We have a lot of requests to support Rocky and Alma in various system roles. The
first part of adding support is adding `vars/` files for these platforms. In
almost every case, for a given major version N, the vars file RedHat_N.yml can
be used for CentOS, Rocky, and Alma.  Rather than making a copy of the
RedHat_N.yml file, just use a symlink to reduce size and maintenance burden, and
standardize this across all system roles for consistency.
NOTE: OracleLinux is not a strict clone, so we are not going to do this for
OracleLinux at this time.  Support for OracleLinux will need to be done in
separate PRs. For more information, see
https://github.com/linux-system-roles/cockpit/issues/130
Note that there may be more work to be done to the role to fully support Rocky
and Alma.  Many roles …

refactor: Use vars/RedHat_N.yml symlink for CentOS, Rocky, Alma wherever possible

---

playbooks/templates/.github/workflows/tft.yml

Fedora 41 is released, and Fedora 39 will soon be unsupported
Part two - first part did not work

ci: Use Fedora 41, drop Fedora 39 - part two

---

inventory/host_vars/mssql.yml

win_shell is not used in the role since it's #301

Remove mock_modules from mssql

---

inventory/group_vars/active_roles.yml

ansible-plugin-scan is broken due to lack of support for older versions
of python in ci.
One of the main reasons for using this scan is to check if the roles/tests
are using plugins that are not compatible with ansible 2.9.  Since 2.9
is EOL, this is no longer necessary.
The other reason for using the scan is to check that the role/test
author has correctly listed dependencies in meta/collection-requirements.yml
and tests/collection-requirements.yml - that is - that the author has
correctly specified the dependencies for any plugins used that are
not built-in.  This will mostly be caught in CI testing now.

ci: ansible-plugin-scan is disabled for now

---

inventory/host_vars/ad_integration.yml
inventory/host_vars/rhc.yml
inventory/host_vars/selinux.yml
inventory/host_vars/tlog.yml
playbooks/templates/.github/workflows/ansible-lint.yml
playbooks/update_files.yml

There is a new version of ansible-lint - v25.
Newer versions of ansible-lint require the collection requirements to be
installed so it can find the modules/plugins.
Enhance our ansible-lint ci job to provide the collection requirements,
including merging the runtime meta/collection-requirements.yml with
the testing tests/collection-requirements.yml.
This should somewhat mitigate the loss of ansible-plugin-scan.
We have to remove mock_modules that are actually present now.

ci: bump ansible-lint to v25; provide collection requirements for ansible-lint

---

inventory/group_vars/active_roles.yml
inventory/host_vars/aide.yml
inventory/host_vars/metrics.yml
inventory/host_vars/network.yml
playbooks/include_files/storage_contributing.md
playbooks/templates/.codespellrc
playbooks/templates/.github/workflows/codespell.yml
playbooks/templates/.github/workflows/tft_citest_bad.yml
playbooks/update_files.yml

* You can ignore words inline by adding a comment like `# codespell:ignore word`.
* You can ignore words by adding them to the `.codespell_ignores` file.
* You can ignore files and directories by adding them with `skip = ` to the `.codespellrc` file.

ci: Check spelling with codespell

---

playbooks/templates/.github/workflows/python-unit-test.yml

Ubuntu 20.04 will be removed from GH actions by April 1, 2025. We can switch to 22.04 which still has Python 2.

ci: Bump Ubuntu version for Python unit tests

---

playbooks/role_templates/ha_cluster/.github/workflows/python-unit-test.yml

* add new pcs versions to test matrix
* fix to be able to install pcs-0.12 branch
This is a follow-up for https://github.com/linux-system-roles/ha_cluster/pull/253

ci: update ha_cluster unit tests workflow

---

playbooks/templates/plans/test_playbooks_parallel.fmf

This forces having to have a system libvirt instance, but that is incompatible with running tests inside of containers/toolbox. It also seems unnecessary: session libvirt networking and the tests work just fine.
Drop the explicit setting and let tmt/testcloud pick its internal default (which is `qemu:///session`). This wasn't relevant for running on Testing Farm anyway.
---
Requiring a system libvirtd instance is an unnecessary requirement (e.g. my laptop doesn't have libvirtd installed at all, I run everything in toolbox). `tmt` defaults to `qemu:///session` for this reason, which is much more flexible and safer, and less demanding.
`tmt run --until report provision --how virtual --image fedora-42` succeeds for me now. It previously failed with
libvirt: XML-RPC error : Failed to connect …

ci: Drop explicit "connection:" for provisioning

---

playbooks/templates/.github/workflows/tft.yml
playbooks/templates/.github/workflows/tft_citest_bad.yml

The tft jobs run inside the RH internal network, and thus have access to a lot of sensitive data. It is very easy to gain "contributor" status in GitHub, you just need to land a single commit (like a typo fix or small doc update), and it is hard to get a list of/control the set of contributors.
Thus restrict the trigger capability to org members and collaborators, which are an explicit list and much easier to control.
---
This isn't an "obvious" choice. If you get lots of drive-by contributions, I recommend to apply this, as it's too much of a risk. If you have a small set of non-org people who send updates regularly, I recommend to put them into the list on https://github.com/linux-system-roles/.github/settings/access . But the situation may be different for you, so please absolutely …

ci: Remove tft trigger capability for contributors

---

inventory/group_vars/active_roles.yml
playbooks/templates/.github/workflows/python-unit-test.yml

Also bump the ancient version in python-unit-test.yml workflow. Actual roles like sudo already have this pinned at 3.4.0.
----
I already tested the sudo and cockpit roles against `tox-lsr@main` yesterday, seemed to work fine.

ci: Bump tox-lsr to 3.5.0

---

playbooks/templates/.github/workflows/qemu-kvm-integration-tests.yml

GitHub workflows recently grew the ability to set up nested QEMU kvm, but without much fanfare (see [1]). It just needs to create the `/dev/kvm` device node, but the host has it enabled and the kernel supports it.
With that we can run the QEMU tox tests. They are not covered anywhere else, and currently have some bugs, so let's cover them in CI and keep them green.
[1] https://github.com/orgs/community/discussions/8305
----
Tested and initially reviewed in https://github.com/linux-system-roles/sudo/pull/46 and https://github.com/linux-system-roles/cockpit/pull/200

ci: Run QEMU tox integration tests in GitHub workflow

---

inventory/group_vars/active_roles.yml
playbooks/templates/.github/workflows/ansible-lint.yml
playbooks/templates/.github/workflows/python-unit-test.yml
playbooks/templates/.github/workflows/qemu-kvm-integration-tests.yml

Without this - what happens is that the new ansible-lint will install
the collection dependencies in the requirements file in the first
place in ANSIBLE_COLLECTIONS_PATH which will be used instead of
the current code that has been converted to collection format.  When
this happens, any modules/plugins that your PR has added will not be
found.
With this fix, ansible-lint will not overwrite the existing code
which has been converted to collection format.
bump tox-lsr version to 3.5.1

ci: ansible-lint needs collection path; tox-lsr 3.5.1

---

playbooks/templates/.github/workflows/qemu-kvm-integration-tests.yml

Some roles produce ansible/test logs which are too large to sensibly/comfortably view in the main workflow log view. Show only the interesting failures there (the lines around `fatal:`) and upload the full logs as artifact.
----
I originally tested this only against the sudo and cockpit rules, both of which produce relatively small test logs. But it's already unwieldy on [firewall](https://github.com/linux-system-roles/firewall/actions/runs/14405081081/job/40399563001), and on storage it's completely unusable.

ci: Avoid too large inline test logs in QEMU/KVM integration test

---

playbooks/templates/.github/workflows/qemu-kvm-integration-tests.yml

The storage roles has too many tests which causes an ENOSPC on the workflow runners, and they also run for too long. This was already applied in https://github.com/linux-system-roles/storage/commit/ae35218b61e0
---
See https://github.com/linux-system-roles/storage/pull/520#pullrequestreview-2782724748

ci: Skip NVME/SCSI in QEMU GH workflows

---

inventory/group_vars/active_roles.yml

https://github.com/linux-system-roles/tox-lsr/releases/tag/3.7.0 only changes `runcontainer.sh`, which we don't run in CI. So this should not cause any problems. Nevertheless, I tested it in https://github.com/linux-system-roles/sudo/pull/53 and https://github.com/linux-system-roles/cockpit/pull/213.
This paves the way for setting up bootc container build tests/fixes.

ci: Bump tox-lsr to 3.7.0

---

playbooks/templates/.github/workflows/qemu-kvm-integration-tests.yml

Sometimes tests fail with "An exception occurred during task execution." instead of "fatal:". Catch this case as well.
---
Spotted in https://github.com/linux-system-roles/cockpit/pull/212 where the [initial run](https://github.com/linux-system-roles/cockpit/actions/runs/14637439347/job/41071741897?pr=212#step:12:1) didn't show the actual failure of tests_port2.yml. I added this commit to that PR as well, and the [new run with that commit](https://github.com/linux-system-roles/cockpit/actions/runs/14637916143/job/41073261668?pr=212#step:12:115) shows the proper error.

ci: Show exceptions in Ansible logs

---

playbooks/templates/.github/workflows/qemu-kvm-integration-tests.yml

previous commit was missing raw/endraw blocks

add raw/endraw around matrix variable references

---

inventory/group_vars/active_roles.yml
playbooks/templates/.github/workflows/python-unit-test.yml
playbooks/templates/.github/workflows/qemu-kvm-integration-tests.yml
playbooks/templates/.github/workflows/tft.yml

NOTE: This also requires upgrading to tox-lsr 3.11.0
Ansible 2.19 will be released soon and has some changes which will
require fixes in system roles.  This adds 2.19 to our testing matrix
on fedora 42 so that we can start addressing these issues.
python 3.13 is now being used on some platforms.
Using ansible-core 2.18 requires using py311 for pylint and other
python checkers.

ci: Use ansible 2.19 for fedora 42 testing; support python 3.13

---

playbooks/templates/.github/workflows/qemu-kvm-integration-tests.yml

On some versions of ansible/jinja, the YAML format does not work, so use
the JSON format to pass in __bootc_validation

ci: use JSON format for __bootc_validation
